/**
 * The file is generated by SPADAR CLI v. 0.1.0-alpha.1
 * DO NOT EDIT IT MANUALLY because it could be automatically rewritten
 **/

import schema from './schema'

import connector0 from './connectors/openai'

export default {
  name: 'spadar-adapter',
  version: '1.0.0',
  schema: schema,
  connectors: {
    "openai": connector0,
  }
}